### ISSUE TITLE
Challenge "Find all books published by 'No Starch Press'"

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/postgres-workshop#4]
I think the expected results is wrong? Or the challenge is wrong?
This is what it looks like:

##### Expected result

name | name
--- | ---
McGraw-Hill | Java in Japanese
McGraw-Hill | Ruby Gems
McGraw-Hill | CoffeeScript in Java
McGraw-Hill | Swift in 10 Days

presumably the challenge should ask for books published by 'McGraw-Hill'

**Comment by tbtommyb** [comment]
Good catch, sorry I had used a different publisher in the solution.
